### ISSUE TITLE
NativeModules.RNRadar is undefined

### ISSUE THREAD

**Issue by phil-andrews** [radarlabs/react-native-radar#51]
**Describe the bug**
When running on the iOS emulator any Radar function produces a "NativeModules.RNRadar is undefined" error. I have followed the SDK instructions for iOS. I have not installed for Android.

The app, which is just the basic rn template app, runs fine until I call Radar.

**To Reproduce**
1. Start clean project using rn typescript template.
2. Follow SDK installation instructions from Radar docs.
3. Install RN package and follow installation instructions.
4. Call Radar from `App.tsx` in `componentDidMount`.

**Expected behavior**
Radar functions to be available.

**Screenshots**
<img width="414" alt="screen shot 2018-12-16 at 9 30 55 pm" src="https://user-images.githubusercontent.com/14335126/50063327-ed92c400-0179-11e9-8086-b7d61368b180.png">
<img width="788" alt="screen shot 2018-12-16 at 9 31 37 pm" src="https://user-images.githubusercontent.com/14335126/50063347-fd120d00-0179-11e9-91f7-9278f34e28e0.png">
<img width="1076" alt="screen shot 2018-12-16 at 9 32 36 pm" src="https://user-images.githubusercontent.com/14335126/50063375-203cbc80-017a-11e9-8ca4-3d07cd7a8ac7.png">

**Metadata (please complete the following information):**
    "react-native": "0.57.8",
    "react-native-radar": "^2.1.2"
    emulator XR
    xCode 10

**Update:**
In the Plist screenshot you'll see an empty string for one of the privacy settings. I put in a string and it didn't change anything.

The errors in `AppDelegate` don't have an effect at runtime.

**Comment by coolbrow** [comment]
Have you installed the native dependencies with `react-native link react-native-radar`?

**Comment by phil-andrews** [comment]
I have linked with `react-native link react-native-radar`.

<img width="1391" alt="screen shot 2018-12-17 at 6 08 02 pm" src="https://user-images.githubusercontent.com/14335126/50121422-c1814c80-0226-11e9-877b-248a25aa22dd.png">

**Comment by phil-andrews** [comment]
<img width="266" alt="screen shot 2018-12-17 at 6 36 05 pm" src="https://user-images.githubusercontent.com/14335126/50122476-a1ec2300-022a-11e9-96e2-9d876c569b4b.png">

**Comment by coolbrow** [comment]
Yeah, this is very odd as that native could shouldn't even compile; the string literal in `[Radar initializeWithPublishableKey:"key"]` should fail, should be `[Radar initializeWithPublishableKey:@"key"]`. I've noticed that react native builds can fail but the toolchain still pushes an old version of the `.app` to the simulator, its worth double checking that your build is succeeding. 

However, that issue seems separate since your error is caught in the JS runtime. Normally this would mean the `RNRadar` ios module isn't being linked and thus registered so no module is found at runtime. In your case, the linking appears to be happening so either the registration (with react native macros) isn't happening or possibly compilation in general (evidenced by the syntax error not being caught).

**Comment by phil-andrews** [comment]
That was it. Showing my lack of Obj-C chops it was the `@`. Funny that didn't fail. But alright, we're up and running now.

**Comment by coolbrow** [comment]
Happy that fixed it! Sorry about the confusion, the error messages from React Native sometimes are way off 😝

**Comment by phil-andrews** [comment]
No worries, thanks for the help!
